name: Bug Report
description: Report something that isn't working
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug! Fill in the details below.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Clear description of what happened.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: LocalDuck version
      description: "Output of `localduck version`"
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      description: "Output of `python --version`"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true
